###############################################################################
# Observability: SNS topic, CloudWatch alarms, dashboard
###############################################################################

data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

locals {
  alarm_actions = [aws_sns_topic.alarms.arn]
  gib           = 1073741824
}

# ----------------------------------------------------------------------------
# SNS
# NOTE: the topic is intentionally not encrypted with alias/aws/sns - CloudWatch
# alarms cannot publish to topics encrypted with that AWS managed key. Use a
# customer managed key with a cloudwatch.amazonaws.com grant if encryption is
# required.
# ----------------------------------------------------------------------------

resource "aws_sns_topic" "alarms" {
  name = "${var.name_prefix}-alarms"

  tags = var.tags
}

data "aws_iam_policy_document" "alarms_topic" {
  statement {
    sid       = "AllowCloudWatchAlarms"
    actions   = ["sns:Publish"]
    resources = [aws_sns_topic.alarms.arn]

    principals {
      type        = "Service"
      identifiers = ["cloudwatch.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceAccount"
      values   = [data.aws_caller_identity.current.account_id]
    }
  }
}

resource "aws_sns_topic_policy" "alarms" {
  arn    = aws_sns_topic.alarms.arn
  policy = data.aws_iam_policy_document.alarms_topic.json
}

resource "aws_sns_topic_subscription" "email" {
  for_each = toset(var.alarm_emails)

  topic_arn = aws_sns_topic.alarms.arn
  protocol  = "email"
  endpoint  = each.value
}

# ----------------------------------------------------------------------------
# ALB
# ----------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "alb_elb_5xx" {
  alarm_name          = "${var.name_prefix}-alb-elb-5xx"
  alarm_description   = "5xx responses generated by the ALB itself (no healthy target, timeouts)."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.alb_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  for_each = var.target_groups

  alarm_name          = "${var.name_prefix}-${each.key}-target-5xx"
  alarm_description   = "5xx responses returned by the ${each.key} targets."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.alb_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = each.value.arn_suffix
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

# TargetResponseTime is measured until the target starts responding, so long
# lived SSE streams do not inflate it.
resource "aws_cloudwatch_metric_alarm" "target_p95_latency" {
  for_each = var.target_groups

  alarm_name          = "${var.name_prefix}-${each.key}-p95-latency"
  alarm_description   = "p95 target response time of ${each.key} above ${each.value.p95_latency_threshold_seconds}s."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "TargetResponseTime"
  extended_statistic  = "p95"
  period              = 300
  evaluation_periods  = 3
  datapoints_to_alarm = 2
  threshold           = each.value.p95_latency_threshold_seconds
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = each.value.arn_suffix
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "unhealthy_hosts" {
  for_each = var.target_groups

  alarm_name          = "${var.name_prefix}-${each.key}-unhealthy-hosts"
  alarm_description   = "At least one unhealthy ${each.key} target."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "UnHealthyHostCount"
  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 5
  threshold           = 1
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = each.value.arn_suffix
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

# ----------------------------------------------------------------------------
# ECS
# ----------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "ecs_cpu" {
  for_each = var.ecs_services

  alarm_name          = "${var.name_prefix}-ecs-${each.key}-cpu"
  alarm_description   = "ECS service ${each.value} CPU above ${var.cpu_alarm_threshold}% (autoscaling is not keeping up or is at max)."
  namespace           = "AWS/ECS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = var.cpu_alarm_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    ClusterName = var.ecs_cluster_name
    ServiceName = each.value
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "ecs_memory" {
  for_each = var.ecs_services

  alarm_name          = "${var.name_prefix}-ecs-${each.key}-memory"
  alarm_description   = "ECS service ${each.value} memory above ${var.memory_alarm_threshold}%."
  namespace           = "AWS/ECS"
  metric_name         = "MemoryUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = var.memory_alarm_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    ClusterName = var.ecs_cluster_name
    ServiceName = each.value
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

# ----------------------------------------------------------------------------
# RDS
# ----------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "rds_cpu" {
  alarm_name          = "${var.name_prefix}-rds-cpu"
  alarm_description   = "RDS CPU above ${var.cpu_alarm_threshold}%."
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = var.cpu_alarm_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    DBInstanceIdentifier = var.rds_instance_id
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "rds_connections" {
  alarm_name          = "${var.name_prefix}-rds-connections"
  alarm_description   = "RDS connection count close to max_connections (check pool sizes x task count)."
  namespace           = "AWS/RDS"
  metric_name         = "DatabaseConnections"
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 2
  threshold           = var.rds_max_connections_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    DBInstanceIdentifier = var.rds_instance_id
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "rds_free_storage" {
  alarm_name          = "${var.name_prefix}-rds-free-storage"
  alarm_description   = "RDS free storage below ${var.rds_free_storage_threshold_gib} GiB."
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  statistic           = "Minimum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.rds_free_storage_threshold_gib * local.gib
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "breaching"

  dimensions = {
    DBInstanceIdentifier = var.rds_instance_id
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

# ----------------------------------------------------------------------------
# Redis
# ----------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "redis_evictions" {
  for_each = toset(var.redis_cluster_ids)

  alarm_name          = "${var.name_prefix}-redis-evictions-${each.value}"
  alarm_description   = "Redis is evicting keys on ${each.value}: memory pressure, consider a larger node type."
  namespace           = "AWS/ElastiCache"
  metric_name         = "Evictions"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    CacheClusterId = each.value
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "redis_memory" {
  for_each = toset(var.redis_cluster_ids)

  alarm_name          = "${var.name_prefix}-redis-memory-${each.value}"
  alarm_description   = "Redis memory usage above 85% on ${each.value}. The Celery broker shares this instance."
  namespace           = "AWS/ElastiCache"
  metric_name         = "DatabaseMemoryUsagePercentage"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 2
  threshold           = 85
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    CacheClusterId = each.value
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

# ----------------------------------------------------------------------------
# OpenSearch (optional)
# ----------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "opensearch_red" {
  count = var.enable_opensearch_alarms ? 1 : 0

  alarm_name          = "${var.name_prefix}-opensearch-red"
  alarm_description   = "OpenSearch cluster status is red: at least one primary shard is unassigned."
  namespace           = "AWS/ES"
  metric_name         = "ClusterStatus.red"
  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 3
  threshold           = 1
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    DomainName = var.opensearch_domain_name
    ClientId   = data.aws_caller_identity.current.account_id
  }

  alarm_actions = local.alarm_actions
  ok_actions    = local.alarm_actions

  tags = var.tags
}

# ----------------------------------------------------------------------------
# Dashboard
# ----------------------------------------------------------------------------

locals {
  region = data.aws_region.current.name

  widget_alb_requests = {
    type   = "metric"
    x      = 0
    y      = 0
    width  = 12
    height = 6
    properties = {
      title   = "ALB requests / 5xx"
      region  = local.region
      view    = "timeSeries"
      stacked = false
      period  = 60
      stat    = "Sum"
      metrics = concat(
        [["AWS/ApplicationELB", "RequestCount", "LoadBalancer", var.alb_arn_suffix]],
        [["AWS/ApplicationELB", "HTTPCode_ELB_5XX_Count", "LoadBalancer", var.alb_arn_suffix]],
        [for k, tg in var.target_groups : ["AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", "LoadBalancer", var.alb_arn_suffix, "TargetGroup", tg.arn_suffix]],
      )
    }
  }

  widget_alb_latency = {
    type   = "metric"
    x      = 12
    y      = 0
    width  = 12
    height = 6
    properties = {
      title   = "Target response time p95"
      region  = local.region
      view    = "timeSeries"
      stacked = false
      period  = 60
      stat    = "p95"
      metrics = [for k, tg in var.target_groups : ["AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", var.alb_arn_suffix, "TargetGroup", tg.arn_suffix]]
    }
  }

  widget_ecs_cpu = {
    type   = "metric"
    x      = 0
    y      = 6
    width  = 12
    height = 6
    properties = {
      title   = "ECS CPU %"
      region  = local.region
      view    = "timeSeries"
      stacked = false
      period  = 60
      stat    = "Average"
      metrics = [for k, svc in var.ecs_services : ["AWS/ECS", "CPUUtilization", "ClusterName", var.ecs_cluster_name, "ServiceName", svc]]
    }
  }

  widget_ecs_memory = {
    type   = "metric"
    x      = 12
    y      = 6
    width  = 12
    height = 6
    properties = {
      title   = "ECS memory %"
      region  = local.region
      view    = "timeSeries"
      stacked = false
      period  = 60
      stat    = "Average"
      metrics = [for k, svc in var.ecs_services : ["AWS/ECS", "MemoryUtilization", "ClusterName", var.ecs_cluster_name, "ServiceName", svc]]
    }
  }

  widget_rds = {
    type   = "metric"
    x      = 0
    y      = 12
    width  = 12
    height = 6
    properties = {
      title   = "RDS CPU / connections"
      region  = local.region
      view    = "timeSeries"
      stacked = false
      period  = 60
      stat    = "Average"
      metrics = [
        ["AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", var.rds_instance_id],
        ["AWS/RDS", "DatabaseConnections", "DBInstanceIdentifier", var.rds_instance_id, { yAxis = "right" }],
      ]
    }
  }

  widget_redis = {
    type   = "metric"
    x      = 12
    y      = 12
    width  = 12
    height = 6
    properties = {
      title   = "Redis memory % / evictions"
      region  = local.region
      view    = "timeSeries"
      stacked = false
      period  = 60
      stat    = "Average"
      metrics = concat(
        [for id in var.redis_cluster_ids : ["AWS/ElastiCache", "DatabaseMemoryUsagePercentage", "CacheClusterId", id]],
        [for id in var.redis_cluster_ids : ["AWS/ElastiCache", "Evictions", "CacheClusterId", id, { yAxis = "right", stat = "Sum" }]],
      )
    }
  }
}

resource "aws_cloudwatch_dashboard" "this" {
  dashboard_name = "${var.name_prefix}-overview"

  dashboard_body = jsonencode({
    widgets = [
      local.widget_alb_requests,
      local.widget_alb_latency,
      local.widget_ecs_cpu,
      local.widget_ecs_memory,
      local.widget_rds,
      local.widget_redis,
    ]
  })
}
