"""Repository Protocols. Services depend on these, never on SQLAlchemy directly."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date
from typing import Any, Protocol

from app.domain.models import GeoPoint, PlaceCandidate, ScoringProfile, Template
from app.infra.db.models import Course, Event, Place, Purpose, Region, User, UserPreference


class RegionRepository(Protocol):
    async def get_by_slug(self, slug: str) -> Region | None: ...
    async def list_active(self, parent_slug: str | None, q: str | None) -> list[tuple[Region, int]]: ...
    async def nearest_active(self, point: GeoPoint) -> Region | None: ...


class ConfigRepository(Protocol):
    async def get_purpose(self, code: str) -> Purpose | None: ...
    async def list_purposes(self) -> list[Purpose]: ...
    async def templates_for(self, purpose_id: int, purpose_code: str) -> list[Template]: ...
    async def scoring_profile(self, purpose_id: int, purpose_code: str) -> ScoringProfile: ...
    async def tag_affinity(self, purpose_id: int) -> dict[str, float]: ...


class PlaceRepository(Protocol):
    async def fetch(
        self, role: str, origin: GeoPoint, radius_m: float, on_date: date, name_words: Sequence[str] = ()
    ) -> list[PlaceCandidate]: ...
    async def candidates_by_ids(self, place_ids: Sequence[int]) -> dict[int, PlaceCandidate]: ...
    async def event_candidates_by_ids(self, event_ids: Sequence[int]) -> dict[int, PlaceCandidate]: ...
    async def category_rating_avg(self, region_id: int | None) -> dict[str, float]: ...
    async def get_by_public_id(self, public_id: str) -> Place | None: ...
    async def ids_by_public_ids(self, public_ids: Sequence[str]) -> set[int]: ...
    async def events_near(
        self, origin: GeoPoint, radius_m: float, on_date: date
    ) -> list[tuple[Event, float]]: ...
    async def bump_recommend_count(self, place_ids: Sequence[int]) -> None: ...


class CourseRepository(Protocol):
    async def add(self, course: Course) -> Course: ...
    async def get_by_public_id(self, public_id: str) -> Course | None: ...
    async def siblings(self, course: Course) -> list[Course]: ...
    async def list_for_user(self, user_id: int, cursor: int | None, limit: int) -> list[Course]: ...
    async def delete(self, course: Course) -> None: ...


class UserRepository(Protocol):
    async def get_by_public_id(self, public_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_preference(self, user_id: int) -> UserPreference | None: ...
    async def upsert_oauth_user(
        self, provider: str, provider_user_id: str, email: str | None, nickname: str | None
    ) -> User: ...


JsonDict = dict[str, Any]
