"""initial schema — every ERD table (docs/02-erd.md)

Revision ID: 0001
Revises:
Create Date: 2026-09-21

Portable: runs on PostgreSQL (production) and SQLite (local). PostGIS `geog` generated columns and
GIST indexes are created only when the dialect is postgresql. Monthly partitioning of
`recommendation_log` / `audit_log` is an ops step (pg_partman) and intentionally not done here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

GEO_TABLES = {"region": ("center_lng", "center_lat"), "place": ("lng", "lat"), "event": ("lng", "lat")}


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _create_postgis() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    for table, (lng, lat) in GEO_TABLES.items():
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN geog geography(Point, 4326) "
            f"GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint({lng}, {lat}), 4326)::geography) STORED"
        )
        op.execute(f"CREATE INDEX ix_{table}_geog ON {table} USING GIST (geog)")
    op.execute("ALTER TABLE region ADD COLUMN boundary geography(MultiPolygon, 4326)")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key')),
    sa.UniqueConstraint('hash', name=op.f('uq_api_key_hash'))
    )
    op.create_table('category',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('course_role', sa.String(length=16), nullable=False),
    sa.Column('default_stay_min', sa.Integer(), nullable=False),
    sa.Column('provider_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('code', name=op.f('uq_category_code'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_course_role'), ['course_role'], unique=False)

    op.create_table('purpose',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purpose')),
    sa.UniqueConstraint('code', name=op.f('uq_purpose_code'))
    )
    op.create_table('region',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('search_keywords', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['region.id'], name=op.f('fk_region_parent_id_region'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region')),
    sa.UniqueConstraint('slug', name=op.f('uq_region_slug'))
    )
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index('ix_region_parent', ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_status'), ['status'], unique=False)

    op.create_table('search_outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('op', sa.String(length=8), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_outbox'))
    )
    with op.batch_alter_table('search_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_outbox_processed_at'), ['processed_at'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_group'), ['group'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delete_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('public_id', name=op.f('uq_user_public_id'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_audit_log_actor_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_log_entity', ['entity', 'entity_id'], unique=False)

    op.create_table('banner',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('placement', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_banner_region_id_region'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banner'))
    )
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banner_placement'), ['placement'], unique=False)

    op.create_table('chat_session',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_session_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session')),
    sa.UniqueConstraint('public_id', name=op.f('uq_chat_session_public_id'))
    )
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_user_id'), ['user_id'], unique=False)

    op.create_table('course_template',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('purpose_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('time_band', sa.String(length=16), nullable=False),
    sa.Column('min_budget_per_person', sa.Integer(), nullable=False),
    sa.Column('party_min', sa.SmallInteger(), nullable=False),
    sa.Column('party_max', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], name=op.f('fk_course_template_purpose_id_purpose'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_template')),
    sa.UniqueConstraint('code', name=op.f('uq_course_template_code'))
    )
    with op.batch_alter_table('course_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_template_purpose_id'), ['purpose_id'], unique=False)

    op.create_table('ingestion_job',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cursor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_ingestion_job_region_id_region'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_job'))
    )
    with op.batch_alter_table('ingestion_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_job_region_id'), ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_job_status'), ['status'], unique=False)

    op.create_table('oauth_account',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_oauth_account_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_account')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_account_provider_user')
    )
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_account_user_id'), ['user_id'], unique=False)

    op.create_table('place',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('road_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('price_per_person', sa.Integer(), nullable=True),
    sa.Column('price_tier', sa.SmallInteger(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name=op.f('ck_place_lat_range')),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name=op.f('ck_place_lng_range')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_place_category_id_category')),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_place_region_id_region')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place')),
    sa.UniqueConstraint('public_id', name=op.f('uq_place_public_id'))
    )
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.create_index('ix_place_lat_lng', ['lat', 'lng'], unique=False)
        batch_op.create_index('ix_place_region_status_category', ['region_id', 'status', 'category_id'], unique=False)
        batch_op.create_index('ix_place_status_price', ['status', 'price_per_person'], unique=False)

    op.create_table('purpose_tag_affinity',
    sa.Column('purpose_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], name=op.f('fk_purpose_tag_affinity_purpose_id_purpose'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_purpose_tag_affinity_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purpose_id', 'tag_id', name=op.f('pk_purpose_tag_affinity'))
    )
    op.create_table('recommendation_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('purpose_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('scoring_profile_version', sa.String(length=64), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('selected_courses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], name=op.f('fk_recommendation_log_purpose_id_purpose')),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_recommendation_log_region_id_region')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_recommendation_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_log'))
    )
    with op.batch_alter_table('recommendation_log', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_log_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_log_request_id'), ['request_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('scoring_profile',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('purpose_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('experiment_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], name=op.f('fk_scoring_profile_purpose_id_purpose'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_profile')),
    sa.UniqueConstraint('purpose_id', name=op.f('uq_scoring_profile_purpose_id'))
    )
    op.create_table('user_preference',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('liked_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('disliked_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('category_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('taste_vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('default_transport', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_preference_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preference'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_message_session_id_chat_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_session_id'), ['session_id'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('purpose_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('party_size', sa.SmallInteger(), nullable=False),
    sa.Column('budget_total', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('total_travel_min', sa.Integer(), nullable=False),
    sa.Column('total_distance_m', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('optimizer', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('tip', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recommendation_log_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], name=op.f('fk_course_purpose_id_purpose')),
    sa.ForeignKeyConstraint(['recommendation_log_id'], ['recommendation_log.id'], name=op.f('fk_course_recommendation_log_id_recommendation_log'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_course_region_id_region')),
    sa.ForeignKeyConstraint(['template_id'], ['course_template.id'], name=op.f('fk_course_template_id_course_template'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_course_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course')),
    sa.UniqueConstraint('public_id', name=op.f('uq_course_public_id'))
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_user_id'), ['user_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_event_category_id_category')),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_event_place_id_place'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_event_region_id_region')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_event_provider_external'),
    sa.UniqueConstraint('public_id', name=op.f('uq_event_public_id'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_region_period', ['region_id', 'starts_on', 'ends_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_status'), ['status'], unique=False)

    op.create_table('menu_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_signature', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_menu_item_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item'))
    )
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_place_id'), ['place_id'], unique=False)

    op.create_table('opening_hour',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dow', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('dow BETWEEN 0 AND 6', name=op.f('ck_opening_hour_dow_range')),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_opening_hour_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_hour')),
    sa.UniqueConstraint('place_id', 'dow', name='uq_opening_hour_place_dow')
    )
    with op.batch_alter_table('opening_hour', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opening_hour_place_id'), ['place_id'], unique=False)

    op.create_table('place_revision',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('admin_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_place_revision_admin_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_place_revision_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_revision'))
    )
    with op.batch_alter_table('place_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_revision_place_id'), ['place_id'], unique=False)

    op.create_table('place_source',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_place_source_place_id_place'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_source')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_place_source_provider_external')
    )
    with op.batch_alter_table('place_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_source_place_id'), ['place_id'], unique=False)

    op.create_table('place_stats',
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('bayes_rating', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_count', sa.Integer(), nullable=False),
    sa.Column('aspect_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('recommend_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('visit_feedback_avg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_place_stats_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', name=op.f('pk_place_stats'))
    )
    op.create_table('place_tag',
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_place_tag_place_id_place'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_place_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'tag_id', name=op.f('pk_place_tag'))
    )
    op.create_table('popular_time',
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dow', sa.SmallInteger(), nullable=False),
    sa.Column('hour', sa.SmallInteger(), nullable=False),
    sa.Column('congestion', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_popular_time_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'dow', 'hour', name=op.f('pk_popular_time'))
    )
    op.create_table('review',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('aspects', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_review_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_review_provider_external')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_place_id'), ['place_id'], unique=False)

    op.create_table('template_slot',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('course_role', sa.String(length=16), nullable=False),
    sa.Column('budget_share', sa.Float(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_order_flexible', sa.Boolean(), nullable=False),
    sa.Column('earliest_start', sa.Time(), nullable=True),
    sa.Column('latest_start', sa.Time(), nullable=True),
    sa.Column('min_slot_budget', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['course_template.id'], name=op.f('fk_template_slot_template_id_course_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_slot')),
    sa.UniqueConstraint('template_id', 'position', name='uq_template_slot_position')
    )
    op.create_table('course_feedback',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('visited', sa.Boolean(), nullable=False),
    sa.Column('actual_spend', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('stop_feedback', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_feedback_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_course_feedback_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_feedback'))
    )
    with op.batch_alter_table('course_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_feedback_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('course_stop',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('course_role', sa.String(length=16), nullable=False),
    sa.Column('arrive_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leave_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('est_price', sa.Integer(), nullable=False),
    sa.Column('travel_min_from_prev', sa.Integer(), nullable=False),
    sa.Column('distance_m_from_prev', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('congestion', sa.Float(), nullable=True),
    sa.Column('slot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_stop_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_course_stop_event_id_event'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_course_stop_place_id_place'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_stop'))
    )
    with op.batch_alter_table('course_stop', schema=None) as batch_op:
        batch_op.create_index('ix_course_stop_course_position', ['course_id', 'position'], unique=False)

    # ### end Alembic commands ###
    if _is_postgres():
        _create_postgis()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_stop', schema=None) as batch_op:
        batch_op.drop_index('ix_course_stop_course_position')

    op.drop_table('course_stop')
    with op.batch_alter_table('course_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_feedback_course_id'))

    op.drop_table('course_feedback')
    op.drop_table('template_slot')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_place_id'))

    op.drop_table('review')
    op.drop_table('popular_time')
    op.drop_table('place_tag')
    op.drop_table('place_stats')
    with op.batch_alter_table('place_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_source_place_id'))

    op.drop_table('place_source')
    with op.batch_alter_table('place_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_revision_place_id'))

    op.drop_table('place_revision')
    with op.batch_alter_table('opening_hour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_hour_place_id'))

    op.drop_table('opening_hour')
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_place_id'))

    op.drop_table('menu_item')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_status'))
        batch_op.drop_index('ix_event_region_period')

    op.drop_table('event')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_status'))

    op.drop_table('course')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_session_id'))

    op.drop_table('chat_message')
    op.drop_table('user_preference')
    op.drop_table('scoring_profile')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_family_id'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('recommendation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_log_request_id'))
        batch_op.drop_index('ix_recommendation_log_created')

    op.drop_table('recommendation_log')
    op.drop_table('purpose_tag_affinity')
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_index('ix_place_status_price')
        batch_op.drop_index('ix_place_region_status_category')
        batch_op.drop_index('ix_place_lat_lng')

    op.drop_table('place')
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_account_user_id'))

    op.drop_table('oauth_account')
    with op.batch_alter_table('ingestion_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_job_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_job_region_id'))

    op.drop_table('ingestion_job')
    with op.batch_alter_table('course_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_template_purpose_id'))

    op.drop_table('course_template')
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_user_id'))

    op.drop_table('chat_session')
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banner_placement'))

    op.drop_table('banner')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))

    op.drop_table('audit_log')
    op.drop_table('user')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_group'))

    op.drop_table('tag')
    with op.batch_alter_table('search_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_outbox_processed_at'))

    op.drop_table('search_outbox')
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_status'))
        batch_op.drop_index('ix_region_parent')

    op.drop_table('region')
    op.drop_table('purpose')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_course_role'))

    op.drop_table('category')
    op.drop_table('api_key')
    # ### end Alembic commands ###
